### ISSUE TITLE
Default configuration is super high IOPS cost

### ISSUE THREAD

**Issue by mperrotta** [awslabs/dynamodb-titan-storage-backend#15]
We got dinged because the default configuration provisions very high Dynamo DB IOPS which are charged per hour whether you use them or not. Maybe the default should be the lowest possible IOPS with a prominent warning/instruction on how to raise it?

**Comment by concretevitamin** [comment]
+1

**Comment by amcp** [comment]
I will reduce the default configuration to stay within the confines of the free tier.

**Comment by amcp** [comment]
To keep the 6 KCVStores in 0.5.4 within the free tier, the R/W provisioning should be 4 reads and 4 writes per second.

**Comment by amcp** [comment]
https://github.com/awslabs/dynamodb-titan-storage-backend/commit/d0e732e6ac12953778f0b61791a06a7f0a57168b

**Comment by amcp** [comment]
As soon as I increase the point version number of the POM and publish new Maven artifacts, I will close this issue. Thank you for your feedback.

**Comment by amcp** [comment]
published new maven artifacts at version 1.0.1. closing
