### ISSUE TITLE
Investigate issues with select() in Graph of Gods walkthrough in Titan

### ISSUE THREAD

**Issue by amcp** [awslabs/dynamodb-titan-storage-backend#177]
#167 discovered a discrepancy but it is not clear if the discrepancy is related to JG or not.

**Comment by pluradj** [comment]
There was a bug in the Titan docs. It is [corrected](https://github.com/JanusGraph/janusgraph/commit/6f82981962e8f75ffa5820201e38e50d9e9d25ab) in the JanusGraph docs.

```g.V(pluto).out('brother').as('god').out('lives').as('place').select()```

should be 

```g.V(pluto).out('brother').as('god').out('lives').as('place').select('god', 'place')```

**Comment by amcp** [comment]
Closing as the Titan docs were buggy. Thank you @pluradj
