### ISSUE TITLE
java.math.BigDecimal is not supported

### ISSUE THREAD

**Issue by bobzsj87** [awslabs/dynamodb-titan-storage-backend#190]
I deployed on the cloud dynamodb using the CloudFormation, and try to play with the basic property using `gremlin> :> g.E().hasLabel("likes").property("weight", 0.4)`. 

But got this error: 
`Property value [0.4] is of type class java.math.BigDecimal is not supported`

**Comment by bobzsj87** [comment]
Seems it is a Titan problem: https://groups.google.com/forum/#!topic/aureliusgraphs/BWSWd-pV9m4
By adding` :> double a=0.4; g.E().hasLabel("likes").property("weight", a)` solves the problem

**Comment by amcp** [comment]
@bobzsj87 you might want to try using the JanusGraph compatible version available [here](https://github.com/awslabs/dynamodb-titan-storage-backend/tree/master).
