### ISSUE TITLE
TimeoutException when adding new vertices during waitForIDBlockGetter

### ISSUE THREAD

**Issue by ingojaeckel** [awslabs/dynamodb-titan-storage-backend#20]
Hi,

I am seeing the following timeout exception when trying to add new vertexes to my Titan graph. This happens on the real DynamoDB service https://dynamodb.us-west-2.amazonaws.com (not on DynamoDB local). I am using com.amazonaws:dynamodb-titan100-storage-backend:1.0.0.

Any ideas what is causing this?

Thanks,
Ingo

ERROR [2015-12-15 22:04:17,220] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 37c9f0de45e92a75
! java.util.concurrent.TimeoutException: null
! at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[na:1.8.0_65]
! at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.waitForIDBlockGetter(StandardIDPool.java:129) ~[app.jar:1.0.0-SNAPSHOT]
! ... 75 common frames omitted
! Causing: com.thinkaurelius.titan.core.TitanException: ID block allocation on partition(3)-namespace(0) timed out in 2.000 min
! at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.waitForIDBlockGetter(StandardIDPool.java:150) ~[app.jar:1.0.0-SNAPSHOT]
! at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextBlock(StandardIDPool.java:172) ~[app.jar:1.0.0-SNAPSHOT]
! at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextID(StandardIDPool.java:198) ~[app.jar:1.0.0-SNAPSHOT]
! at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:320) ~[app.jar:1.0.0-SNAPSHOT]
! at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:169) ~[app.jar:1.0.0-SNAPSHOT]
! at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:140) ~[app.jar:1.0.0-SNAPSHOT]
! at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:437) ~[app.jar:1.0.0-SNAPSHOT]
! at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addVertex(StandardTitanTx.java:507) ~[app.jar:1.0.0-SNAPSHOT]
! at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addVertex(StandardTitanTx.java:525) ~[app.jar:1.0.0-SNAPSHOT]
! at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addVertex(StandardTitanTx.java:521) ~[app.jar:1.0.0-SNAPSHOT]
! at com.thinkaurelius.titan.graphdb.tinkerpop.TitanBlueprintsGraph.addVertex(TitanBlueprintsGraph.java:150) ~[app.jar:1.0.0-SNAPSHOT]

**Comment by amcp** [comment]
Hi Ingo, are you using the Gremlin Server zip we provide, or are you just using the Maven dependency in your own application? I just did a test of the server zip and I was able to write a vertex without timeouts.

**Comment by ingojaeckel** [comment]
I use the latest version of the dependency from Maven central. I will try to create a reproducible example. Everything works fine on DynamoDB local. But when I am deploying this and running against real DynamoDB it fails *sometimes* when adding vertices concurrently.

**Comment by ingojaeckel** [comment]
@amcp would you expect this when running out of read/write provisioning? This was happening on a table that was only provisioned at 1 r/w unit. And CloudWatch showed that my test used exactly 100% of the read provisioning.

**Comment by amcp** [comment]
Seems likely that increasing the read/write capacity of the table in question would solve the problem. From the stack trace, I suspect the titan_ids table is the one that needs more provisioned IOPS. Could you try and report back please?

**Comment by ingojaeckel** [comment]
I will close this as I have not seen this anymore after increasing provisioning on titan_ids and other tables.
