### ISSUE TITLE
Very slow graph insertions during local development

### ISSUE THREAD

**Issue by ingojaeckel** [awslabs/dynamodb-titan-storage-backend#21]
Is it normal that inserting < 20 vertices and < 30 edges between them takes 1-2 minutes to complete? I am running a test locally with dynamodb-titan100-storage-backend:1.0.0 against DynamoDB Local. The graph.tx().commit() takes several minutes to complete on a 2014 MacBook Pro.

Is this expected? Do you have an idea of where the bottleneck is (Titan, Dynamo)? Can I do anything to speed this up?

After inserting those nodes, queries against the index take ~1s first and then few milliseconds once the local cache has been populated.

Thanks,
Ingo

**Comment by rlcomte** [comment]
I don't think that behavior is to be expected. We experience subsecond
response times for inserting a collection of vertices and edges (albeit
combined in one call).
We did experience longer durations in both updates and queries before we
added property key indexing on the uuid of our vertices.
You should check the log files for those warnings.

Rine

Met vriendelijke groet, kind regards,

Rine le Comte

M rlcomte@gmail.com B Medium <https://medium.com/@rinelecomte>

**Comment by ingojaeckel** [comment]
Looks like this was a configuration issue on my end. Increasing the {read,write}-rate and capacity-{read,write} values fixed this issue.

        conf.setProperty("storage.dynamodb.stores.edgestore.capacity-read", "100");
        conf.setProperty("storage.dynamodb.stores.edgestore.read-rate", "100");
        conf.setProperty("storage.dynamodb.stores.edgestore.capacity-write", "100");
        conf.setProperty("storage.dynamodb.stores.edgestore.write-rate", "100");
        conf.setProperty("storage.dynamodb.stores.graphindex.capacity-read", "100");
        conf.setProperty("storage.dynamodb.stores.graphindex.read-rate", "100");
        conf.setProperty("storage.dynamodb.stores.graphindex.capacity-write", "100");
        conf.setProperty("storage.dynamodb.stores.graphindex.write-rate", "100");
