### ISSUE TITLE
Start dynamodb local fail

### ISSUE THREAD

**Issue by itman85** [awslabs/dynamodb-titan-storage-backend#24]
It worked without any problem before, but today i started it as usual and got this error. I did not change anything. I started dynamodb local like this
$mvn test -Pstart-dynamodb-local
And got error:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Amazon DynamoDB Storage Backend for Titan 1.0.0
[INFO] ------------------------------------------------------------------------
[WARNING] Could not transfer metadata com.amazonaws:aws-java-sdk-dynamodb/maven-metadata.xml from/to maven-s3-release-repo (s3://dynamodblocal/release): Cannot access s3://dynamodblocal/release with type default using the available connector factories: BasicRepositoryConnectorFactory
[WARNING] Could not transfer metadata com.amazonaws:aws-java-sdk-dynamodb/maven-metadata.xml from/to maven-s3-snapshot-repo (s3://dynamodblocal/snapshot): Cannot access s3://dynamodblocal/snapshot with type default using the available connector factories: BasicRepositoryConnectorFactory
[WARNING] Failure to transfer com.amazonaws:aws-java-sdk-dynamodb/maven-metadata.xml from s3://dynamodblocal/release was cached in the local repository, resolution will not be reattempted until the update interval of maven-s3-release-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.amazonaws:aws-java-sdk-dynamodb/maven-metadata.xml from/to maven-s3-release-repo (s3://dynamodblocal/release): Cannot access s3://dynamodblocal/release with type default using the available connector factories: BasicRepositoryConnectorFactory
[WARNING] Failure to transfer com.amazonaws:aws-java-sdk-dynamodb/maven-metadata.xml from s3://dynamodblocal/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of maven-s3-snapshot-repo has elapsed or updates are forced. Original error: Could not transfer metadata com.amazonaws:aws-java-sdk-dynamodb/maven-metadata.xml from/to maven-s3-snapshot-repo (s3://dynamodblocal/snapshot): Cannot access s3://dynamodblocal/snapshot with type default using the available connector factories: BasicRepositoryConnectorFactory
[INFO] 
[INFO] --- exec-maven-plugin:1.2:exec (default) @ dynamodb-titan100-storage-backend ---
Error: Could not find or load main class com.amazonaws.services.dynamodbv2.local.main.ServerRunner
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.888 s
[INFO] Finished at: 2016-01-08T10:13:42+07:00
[INFO] Final Memory: 14M/157M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2:exec (default) on project dynamodb-titan100-storage-backend: Command execution failed. Process exited with an error: 1(Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by itman85** [comment]
Ok i found a problem. the library DynamoDBLocal 1.10.20 is problem. I back to 1.10.5.1 and it found class com.amazonaws.services.dynamodbv2.local.main.ServerRunner.

**Comment by agaur-aws** [comment]
@itman85  thanks for the update,  we're taking a look.

**Comment by raymolin** [comment]
Hey @itman85, can you remove your locally cached version of the artifacts (e.g. rm -rf ~/.m2/repository/com/amazonaws/DynamoDBLocal/1.10.20/)? Looks like there was some incomplete artifact that got uploaded, but it should be correct now if you perform a fresh pull from the s3 maven repo.

**Comment by itman85** [comment]
@raymolin: thank you, i will take this into account for next time i update libs

**Comment by amitgaur** [comment]
@itman85  can we close this issue out if things are good on your end?

**Comment by agaur-aws** [comment]
@itman85  can we close this issue out if things are resolved on your end?
