### ISSUE TITLE
Running my test suite takes 5 times longer with DynamoDBLocal vs Berkeley. Expected?

### ISSUE THREAD

**Issue by jordi-chacon** [awslabs/dynamodb-titan-storage-backend#26]
Hi,

I have a test suite with some 1100 testcases that do various basic writes and reads on very small graphs (less than 50 vertices). Each test builds its own graph and then runs some queries.

The entire suite takes 2min 25sec to run with Berkeley as backend, while it takes 13min 16sec to run with DynamoDBLocal, using the properties file from your repo (https://github.com/awslabs/dynamodb-titan-storage-backend/blob/1.0.0/src/test/resources/dynamodb-local.properties). Is this performance expected?

I have tried to tweak a few properties to increase the performance. In particular, I have raised all `storage.dynamodb.stores.*.capacity-*` to 1000 and all `storage.dynamodb.stores.*.*-rate` to 1000. Then my test suite ran in 6min 45sec (3 times slower than Berkeley).

Do you have any tips on how I can improve the performance even more or is this really as fast as it gets?

Thanks!

**Comment by amcp** [comment]
DynamoDB Local is a testing and prototyping tool that allows AWS DynamoDB customers to try the service without incurring usage charges. It's implementation differs from the DynamoDB service and does not reflect the performance of the service. I personally have been able to drive loads larger than 40000 WPS to the edgestore when configured with the multiple item data model, when running against the service. So, after you can confirm that your code runs correctly, you can try configuring your code to run against the service.

**Comment by jordi-chacon** [comment]
Ok, thanks for your reply!
