### ISSUE TITLE
Adding support for AWS Elasticsearch as an indexing backend

### ISSUE THREAD

**Issue by ingojaeckel** [awslabs/dynamodb-titan-storage-backend#28]
Currently this library does not support AWS Elasticsearch as an indexing backend due to the issue documented [here](https://groups.google.com/forum/#!topic/aureliusgraphs/tVSw7UiyEyg) and [here](http://stackoverflow.com/questions/33412635/how-to-connect-to-aws-elasticsearch/33425725#33425725). AWS ES only provides a HTTP(S) interface - no TCP. If a ES client that supports HTTP(S) like Jest would be used, this library could be used against AWS ES.

**Comment by amcp** [comment]
Thank you for your research. Absent a titan-es plugin enabled by something like Jest, you will not be able to connect to the AWS ElasticSearch service using the current titan-es plugin. As a workaround, you can use the CloudFormation Template [here](https://s3-ap-northeast-1.amazonaws.com/cm-public-cfn-templates/elasticsearchCluster/elasticSearchCluster-1.0.template) as a starting point for you to set up your own autoscaling (CPU and disk usage driven) ES cluster (this template was discussed in a foreign blog post [here](http://dev.classmethod.jp/cloud/aws-cfn-advent-calendar-2013-elasticsearch/)). You may have to change the version of ES used, as titan-es 1.0.0 uses [ElasticSearch version 1.5.1](https://github.com/thinkaurelius/titan/blob/1.0.0/pom.xml#L88).
