### ISSUE TITLE
Unable to SSH on port 8182

### ISSUE THREAD

**Issue by joebernard** [awslabs/dynamodb-titan-storage-backend#29]
After running the CloudFormation script, the Security Group applied to the EC2 instance only allows access on port 22. Even if I add a custom rule to allow TCP traffic on 8182 the request is still denied:

ssh -o ServerAliveInterval=50 -i ${HOME}/.ec2/SSH.pem -p 8182 ec2-user@ec2-xx-xx-xx-xx.compute-1.amazonaws.com
ssh: connect to host ec2-xx-xx-xx-xx.compute-1.amazonaws.com port 8182: Connection refused

I am able to ssh on port 22 but not 8182. There were no errors during the CloudFormation process.

Also note that the SSH command provided in "outputs" does not specify -p 8182 and attempts to connect to port 22 by default.

What do I need to do to connection on port 8182?

**Comment by otech47** [comment]
Did you end up resolving this?

**Comment by joebernard** [comment]
I had to bypass the issue by opening SSH on default port 22 and running gremlin from the remote EC2.

The other option is to tunnel all local port 8182 traffic to the remote server with SSH:
`ssh -o ServerAliveInterval=50 -nNT -L8182:localhost:8182 -i ${HOME}/.ec2/SSH.pem ec2-user@12.34.56.78`

**Comment by amcp** [comment]
The instructions also tell you to open a tunnel in step 7:
https://github.com/awslabs/dynamodb-titan-storage-backend#run-gremlin-on-gremlin-server-in-ec2-using-a-cloudformation-template

Once cloudformation stack finishes creating, go to the stack's output tab in the AWS CloudFormation console, and you can find the tunnel command.

https://github.com/awslabs/dynamodb-titan-storage-backend/blob/1.0.0/dynamodb-titan-storage-backend-cfn.json#L522

**Comment by amcp** [comment]
One has always been able to open a tunnel according to the instructions in the README. Being able to set up an SSH tunnel implies that you can SSH to the EC2 host, so the instructions also tell you to set the SSH whitelist in step 4 here:
https://github.com/awslabs/dynamodb-titan-storage-backend#run-gremlin-on-gremlin-server-in-ec2-using-a-cloudformation-template
