### ISSUE TITLE
Titan 0.5.4 -> Titan 1.0 compatibility

### ISSUE THREAD

**Issue by sayrer** [awslabs/dynamodb-titan-storage-backend#32]
If there is an existing Titan 0.5.4 DB stored at Amazon, what is the migration path to Titan 1.0?

**Comment by sayrer** [comment]
To be clear, I'm looking for information on storage-compatibility with Titan 0.5.4 / DynamoDB. I understand that the API had breaking changes.

**Comment by underscoretang** [comment]
As it turns out it's not compatible, and moving from 0.5.4 to 1.0 requires a backend migration. Going to attempt to see if this approach will work with the dynamo backend: https://github.com/dkuppitz/openflights

**Comment by amcp** [comment]
The storage formats are not compatible. I asked this question prior to the 1.0 release here:
https://groups.google.com/d/msg/aureliusgraphs/A53p9ZG_k30/bSpGtXyKBAAJ

I think using dkuppitz openflights is a great idea.

Alex
