### ISSUE TITLE
could not find or load main class org.apache.tinkerpop.gremlin.console.console

### ISSUE THREAD

**Issue by adzinthepub** [awslabs/dynamodb-titan-storage-backend#33]
Hi,

I am trying to get the local demo working.

When I try to open a Gremlin shell using:

bin/gremlin.sh

I get the following error:

"could not find or load main class org.apache.tinkerpop.gremlin.console.console"

Any ideas?

I'm running Windows 8.

Thanks for your help.

Cheers

**Comment by amcp** [comment]
picking this up

**Comment by amcp** [comment]
First, if you are running on Windows, you should run the bat file instead.

Try downloading the custom zip which is already provided here:
https://s3.amazonaws.com/dynamodb-titan-us-east-1/dynamodb-titan100-storage-backend-1.0.0-hadoop1.zip

Next, make sure you have Maven and a 64 bit Java 8 JRE installed.
You need Maven to start DynamoDB Local from the command line.
Open Windows Powershell and navigate to where you cloned/downloaded the awslabs/dynamodb-titan-storage-backend repository/zip.
Then issue mvn install to pull the DynamoDB Local dependencies.
Then issue mvn test -Pstart-dynamodb-local

Then, open another Windows Powershell and cd to the directory where you unzipped the custom zip above.
Finally, run bin/gremlin.bat and see if you have any luck.

**Comment by amcp** [comment]
Currently, the gremlin.bat script appears to be broken on Windows:
https://github.com/thinkaurelius/titan/issues/1242

It appears that it will be fixed when Titan 1.1.0 is released; the DynamoDB team can then make a new release that enables running locally on Windows.
Until the Titan 1.1.0 release, I encourage you to run the DynamoDB Storage Backend for Titan in EC2 or on a 64 bit linux VM on your Windows machine.

**Comment by greenguy33** [comment]
I am having the same problem. Just downloaded Gremlin Conslole from http://tinkerpop.apache.org/docs/current/tutorials/getting-started/

Running gremlin.bat, I get the error Error: Could not find or load main class Files

Any news on a fix?

**Comment by greenguy33** [comment]
Fixed the issue myself: I had renamed the Tinkerpop folder.

**Comment by pqrsty** [comment]
Hello, can you please tell how you fixed the issue ? Even I have the same error .. but I am not sure what folder had to be renamed to fix this issue :) Kindly help

**Comment by greenguy33** [comment]
In my case, I believe I had manually renamed a folder accidentally, and needed to revert its name back to the original. If you have not renamed one of the directories in your project, then you may be receiving this error for a different reason than I did.

**Comment by pqrsty** [comment]
okay I see, thank you. I did no rename any folder. I only unzipped the contents, moved to the bin directory and ran gremlin.bat .. It gives that error anyway ..

**Comment by pqrsty** [comment]
Is it ok to put the folder into any directory or should it be in a specific path ? Like in C:\ ? I have put it on my desktop and I am trying to run the gremlin.bat ..

**Comment by mustafaekim** [comment]
I am having the same issue here. Running ".\gremlin.bat" returns "Error: Could not find or load main class Files"
