### ISSUE TITLE
ElasticSearch strange behavior

### ISSUE THREAD

**Issue by touficzayed** [awslabs/dynamodb-titan-storage-backend#34]
Hello,

I'm using Titan 1.0.0 on AWS with DynamoDB as the datastore.

I've defined some indexes for text and string search the following way:

description=mgmt.makePropertyKey('description').dataType(String.class).make();
mgmt.buildIndex('showByDescription',Vertex.class).addKey(description,Mapping.TEXTSTRING.asParameter()).indexOnly(show).buildMixedIndex("search");

In gremlin, when I launch this kind of query:

g.V().hasLabel('show').has('description', textContains('SOME DESCRIPTION'));

I can see that I get some results.

On the other hand I don't succeed to perform exact phrase match. The following queries retrieve nothing, despite I know the data are present.

g.V().hasLabel('show').has('description', 'SOME DESCRIPTION');
g.V().hasLabel('show').has('description', eq('SOME DESCRIPTION'));

I checked directly in elastic search, and I can see that in the titan index, I have 2 types for the 'description' property: 'description', and 'description__STRING'.

I suppose that 'description__STRING' is used for exact phrase match.

Why do the last 2 gremlin queries retrieve nothing? Are the queries wrong? Is there another syntaxt for exact phrase match?

Regards,

Toufic Zayed

**Comment by amcp** [comment]
The comparators (binary predicates) that you are implicitly and explicitly using in the example above are only for exact matches. You can do partial and exact matching whether or not you use Elastic Search. What you are looking for are the contains* predicates. They are a Titan specific extension and can be found here:
https://github.com/thinkaurelius/titan/blob/1349a5edd1149a00da6a37a4584aed25a8164a14/titan-core/src/main/java/com/thinkaurelius/titan/core/attribute/Text.java#L27

You want to use the Text.CONTAINS() predicate. If you set up ES, and have a mixed index on the description property, ElasticSearch may be invoked, as is described in this google groups posting here:
https://groups.google.com/forum/#!searchin/aureliusgraphs/contains/aureliusgraphs/jWlEqTRTSTI/TgB0bERIeWwJ
