### ISSUE TITLE
Opening graph fails while updating provisioned capacity on dynamodb table

### ISSUE THREAD

**Issue by lionelport** [awslabs/dynamodb-titan-storage-backend#40]
The dynamodb titan backend doesn't handle a table in an updating state when opening a new graph. This is a defect in DynamoDBDelegate.createTableAndWaitForActive as when it checks for state, if table exists but is not ACTIVE it attempts to createTable and you get the exception "ResourceInUseException: Table already exists"

Really it should only try to createTable if the table does not exist. If the table exists in the state of CREATING or UPDATING it should just attempt to wait.

This is particularly an issue when trying to use Titan in a EMR as when a new task is started a new graph needs to be opened but if you are attempting to provision more capacity in dynamodb all the new tasks will fail with an exception.

**Comment by amcp** [comment]
fixed [here](https://github.com/awslabs/dynamodb-titan-storage-backend/commit/ea3d646b54ffb8efd3a0cefac704352b3b29e281). Thank you for the report.
