### ISSUE TITLE
Configuration for DynamoDB Hadoop in 0.5.4

### ISSUE THREAD

**Issue by underscoretang** [awslabs/dynamodb-titan-storage-backend#42]
Is there a dynamo equivalent for the hadoop format files for the HadoopFactory configurations in 0.5.4?

http://s3.thinkaurelius.com/docs/titan/0.5.4/hadoop-config-ref.html

We're trying to export a list of specific edges from a production Titan 0.5.4 environment and migrate them to a 1.0.0 env

**Comment by amcp** [comment]
I suggest you use the procedure listed in @dkuppitz [openflights project](https://github.com/dkuppitz/openflights) to migrate 0.5.4 data to 1.0.0;.
