### ISSUE TITLE
What is max-concurrent-operations?

### ISSUE THREAD

**Issue by mohataher** [awslabs/dynamodb-titan-storage-backend#45]
There is no description or explanation of `storage.dynamodb.client.executor.max-concurrent-operations` and how to use it in the docs.

It would be a good idea to add that to the table on README.

Thank you.

**Comment by amcp** [comment]
fixed here: https://github.com/awslabs/dynamodb-titan-storage-backend/blob/1.0.0/README.md#dynamodb-client-executor-configuration-parameters
