### ISSUE TITLE
Graph processing progressively gets slower on titan + dynamoDB (local) as more vertices/edges are added

### ISSUE THREAD

**Issue by triton3** [awslabs/dynamodb-titan-storage-backend#46]
I posted this on SO, but I wonder if this might be a more relevant place to ask this.

I am working with titan 1.0 using AWS dynamoDB local implementation as storage backend on a 16GB machine. My use case involves generating graphs periodically containing vertices & edges in the order of 120K. Every time I generate a new graph in-memory, I check the graph stored in DB and either (i) add vertices/edges that do not exist, or (ii) update properties if they already exist (existence is determined by 'Label' and a 'Value' attribute). Note that the 'Value' property is indexed. Transactions are committed in batches of 500 vertices.

**Problem:** I find that this process gets slower each time I process a new graph (1st graph finished in 45 mins with empty db initially, 2nd took 2.5 hours, 3rd in 3.5 hours, 4th in 6 hours, 5th in 10 hours and so on). In fact, when processing a given graph, it is fairly quick at start time but progressively gets slower (initial batches take 2-4 secs and later on it increases to 100s of seconds for same batch size of 500 nodes; I also see sometimes it takes 1000-2000 secs for a batch). This is the processing time alone (see approach below); commit takes between 8-10 secs always. I configured the jvm heap size to 10G, and I notice that when the app is running it is eventually using up all of it.

**Question:** Is this behavior to be expected? It seems to me something is wrong here (either in my [config](https://dl.dropboxusercontent.com/u/4923794/local-graph.properties) / approach?). Any help or suggestions would be greatly appreciated.

**Approach:**

Starting from the root node of the in-memory graph, I retrieve all child nodes and maintain a queue
For each child node, I check to see if it exists in DB, else create new node, and update some properties

```
 Vertex dbVertex = dbgraph.traversal().V()
    .has(currentVertexInMem.label(), "Value",
            (String) currentVertexInMem.value("Value"))
    .tryNext()
    .orElseGet(() -> createVertex(dbgraph, currentVertexInMem));

    if (dbVertex != null) {
        // Update Properties
        updateVertexProperties(dbgraph, currentVertexInMem, dbVertex);
    }

// Add edge if necessary
if (parentDBVertex != null) {
    GraphTraversal<Vertex, Edge> edgeIt = graph.traversal().V(parentDBVertex).outE()
        .has("EdgeProperty1", eProperty1) // eProperty1 is String input parameter
        .has("EdgeProperty2", eProperty2); // eProperty2 is Long input parameter

    Boolean doCreateEdge = true;
     Edge e = null;
     while (edgeIt.hasNext()) {
         e = edgeIt.next();
         if (e.inVertex().equals(dbVertex)) {
             doCreateEdge = false;
             break;
         }

     if (doCreateEdge) {
         e = parentDBVertex.addEdge("EdgeLabel", dbVertex, "EdgeProperty1", eProperty1, "EdgeProperty2", eProperty2);
     } 
e = null;
it = null;
}

...

if ((processedVertexCount.get() % 500 == 0) 
 || processedVertexCount.get() == verticesToProcess.get()) {                            
graph.tx().commit();
}
```

Create function:

```
public static Vertex createVertex(Graph graph, Vertex clientVertex) {
Vertex newVertex = null; 
switch (clientVertex.label()) {
case "Label 1":
    newVertex = graph.addVertex(T.label, clientVertex.label(), "Value",
            clientVertex.value("Value"), 
            "Property1-1", clientVertex.value("Property1-1"), 
            "Property1-2", clientVertex.value("Property1-2"));
    break;

case "Label 2":
    newVertex = graph.addVertex(T.label, clientVertex.label(), "Value",
            clientVertex.value("Value"), "Property2-1",
            clientVertex.value("Property2-1"),
            "Property2-2", clientVertex.value("Property2-2"));
    break;

default:
    newVertex = graph.addVertex(T.label, clientVertex.label(), "Value",
            clientVertex.value("Value"));
    break;
}
return newVertex;
}
```

**Comment by amcp** [comment]
You should create an index on the vertex property "Value". Otherwise, you have to do a full graph scan on each lookup to find the vertex that matches (O(n^2) in the number of vertices). You can do that with 
`TitanGraph.openManagement().buildIndex("myIndexName", Vertex.class).addKey(...).unique().buildCompositeIndex()`
