### ISSUE TITLE
Issues programmatically sending script requests over ws 

### ISSUE THREAD

**Issue by LovelyHorse** [awslabs/dynamodb-titan-storage-backend#47]
I'm not certain whether this is best posted on the Tinkerpop3 JIRA, Titan 1.x github or here.. So you'll have to forgive me if this is out of place. 

I'm having an immense amount of trouble sending a command via websockets using C++. Logically this shouldn't be too hard, though I think the API is changing so drastically that none of the documentation I find has an accurate explanation of the message structure / format.

I'm using the easywsclient library, and an example of my code (and format) is as follows:

```
std::unique_ptr<WebSocket> ws(WebSocket::from_url("ws://SERVER:8182/"));

string command = "\"[1,2,3,4]\"";
string mime = "\"application/json\"";
string language = "\"gremlin-groovy\"";
string session = "\"\"";
string bindings = "\"\"";
string rebindings = "\"\"";
string op = "\"eval\"";
string processor = "\"org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor\"";
string accept = "\"application/json\"";
string executeHandler;
string request = "\"655BD810-B41E-429D-B78F-3CC5F3B8E9BA\"";

string msg = mime + "|-{" +
    "\"requestId\": " + request + "," +
    "\"op\": " + op + ","  +
    "\"processor\": " + processor + "," +
    "\"args\": {"  +
        "\"gremlin\": " + command + "," +
        "\"bindings\": " + bindings + "," +
        "\"language\": " + language + "," +
        "\"rebindings\": " + rebindings +
    "}" +
"}";

ws->send(msg);
//** then ws->poll and ws->dispatch to retrieve the response
```

To which my erroneous response is:

```
{"requestId":null,"status":{"message":"","code":499,"attributes":{}},"result":{"data":"Invalid OpProcessor requested [null]","meta":{}}}
```

I cannot seem to find any variation of op or processor that returns anything but the above. 

Any help would be greatly appreciated!

**Comment by amcp** [comment]
Try using [Gremlin over HTTP](http://tinkerpop.apache.org/docs/3.0.1-incubating/#_connecting_via_rest) first to reduce the number of moving parts. Also, you can inspect the gremlin server logs and paste in the stack trace on the server side. It may give more insight.

**Comment by amcp** [comment]
This question does not belong on this project. Rather, it belongs on the Tinkerpop JIRA or mailing list because it is a question about Gremlin Server functionality.
