### ISSUE TITLE
how to enable userSuppliedId?

### ISSUE THREAD

**Issue by ijung5399** [awslabs/dynamodb-titan-storage-backend#53]
by calling :> graph.features(), I found that 
> VertexFeatures
>-- MultiProperties: true
>-- MetaProperties: true
>-- AddVertices: true
>-- RemoveVertices: true
>-- UserSuppliedIds: false
>-- AddProperty: true
>-- RemoveProperty: true
>-- NumericIds: true
>-- StringIds: false
>-- UuidIds: false
>-- CustomIds: false
>-- AnyIds: false

I want to enable "userSuppliedId" so that I can have a vertex with id like "http://this/is/id".
Is it possible?

**Comment by amcp** [comment]
It is possible to use user-supplied IDs. Here is an example from the graphdb-benchmarks project:[Configuration](https://github.com/socialsensor/graphdb-benchmarks/pull/13/files#diff-d3834f29d50572cf5cd9c9330ff1209eR112), [actual id assignment](https://github.com/socialsensor/graphdb-benchmarks/pull/13/files#diff-f738a2a69b12bcb97c050e04e4c2f10bR27)
