### ISSUE TITLE
How to restart the titan server?

### ISSUE THREAD

**Issue by brianfoody** [awslabs/dynamodb-titan-storage-backend#55]
Sorry feel like a real idiot asking this but when connected through SSH to the server what is the command to restart the titan server to pick up any config changes? Particularly the gremlin server. The titan / gremlin documentation is so scattered I'm having trouble finding this simple thing.

**Comment by amcp** [comment]
Titan Server is installed in the EC2 instance as a system service. You should be able to SSH into the instance and issue `sudo service gremlin-server stop && sudo service gremlin-server start` to restart the server.
