### ISSUE TITLE
Project stopped building -  Could not resolve dependencies for project- No versions available for com.amazonaws:DynamoDBLocal:jar

### ISSUE THREAD

**Issue by jfstephe** [awslabs/dynamodb-titan-storage-backend#56]
In the last couple of days the mvn install of this project has stopped working. I generally operate within docker containers so my environment is reasonably well managed and consistent. But yesterday I started getting the below error.

I'm seeing in inside and out of docker containers, and I'm noticed [others](http://stackoverflow.com/questions/41995292/error-aws-java-sdk-localdynamodb) mentioning this problem.

Could it be a co-incidence that [this ](https://forums.aws.amazon.com/ann.jspa?annID=3148) was reported?

`[ERROR] Failed to execute goal on project dynamodb-titan100-storage-backend: Could not resolve dependencies for project com.amazonaws:dynamodb-titan100-storage-backend:jar:1.0.0: Failed to collect dependencies for [com.amazonaws:aws-java-sdk-dynamodb:jar:[1.10.5.1,2.0.0) (compile), com.amazonaws:DynamoDBLocal:jar:[1.10.5.1,2.0.0) (compile), com.thinkaurelius.titan:titan-core:jar:1.0.0 (compile), com.thinkaurelius.titan:titan-test:jar:1.0.0 (test), com.thinkaurelius.titan:titan-es:jar:1.0.0 (test), com.codahale.metrics:metrics-core:jar:3.0.1 (compile), au.com.bytecode:opencsv:jar:2.4 (compile), com.fasterxml.jackson.datatype:jackson-datatype-json-org:jar:2.5.3 (compile), org.slf4j:slf4j-log4j12:jar:1.7.5 (compile), org.apache.tinkerpop:gremlin-core:jar:3.0.1-incubating (compile), org.apache.tinkerpop:gremlin-groovy:jar:3.0.1-incubating (test), org.apache.tinkerpop:gremlin-test:jar:3.0.1-incubating (test), org.apache.tinkerpop:gremlin-console:jar:3.0.1-incubating (test)]: No versions available for com.amazonaws:DynamoDBLocal:jar:[1.10.5.1,2.0.0) within specified range -> [Help 1]`

Any ideas?

**Comment by jfstephe** [comment]
Changing the repository to the one in the AWS article means changing the aws.java.sdk.version from 1.10.5.1 to 1.11.0.1. I don't know if that's going to impact anything else?!? Whatever we can do to get this bask ASAP would be great as this is completely screwing me.

**Comment by amcp** [comment]
This issue appears to be fixed now. Please confirm

**Comment by jfstephe** [comment]
Yup. All fixed.  Presumably someone did something to fix it?
Thanks anyway.

**Comment by apivovarov** [comment]
Try using https to access dynamodb-local repo
https://s3-us-west-2.amazonaws.com/dynamodb-local/release

**Comment by apivovarov** [comment]
https://github.com/apivovarov/aws-dynamodb-encryption-java/pull/1
