### ISSUE TITLE
Orphan Threads after shutdown

### ISSUE THREAD

**Issue by pallavjakhotiya** [awslabs/dynamodb-titan-storage-backend#59]
After initiating a start of the dynamoDB

`AmazonDynamoDB dynamodb = null;
		DynamoDBProxyServer server = null;
		System.getProperties().setProperty("sqlite4java.library.path", "build/libs");
		try {
			final String[] localArgs = { "-inMemory", "-sharedDb", "-port", "4567" };
			server = ServerRunner.createServerFromCommandLineArgs(localArgs);
			server.start();
			dynamodb = new AmazonDynamoDBClient();
			dynamodb.setEndpoint("http://localhost:4567");
                       // Insert graph to dynamo
                  } finally {
			// Stop the DynamoDB Local endpoint
			com.amazonaws.http.IdleConnectionReaper.shutdown();
			if (dynamodb != null) {
				dynamodb.shutdown();
			}if (server != null) {
				server.stop();
			}
		}
}`
What we find is there are a couple of Titan threads that remain in the stack and hence the process never exits. Looking at the stack trace it seems there are a couple of processes in sleep which never exit. Can you please help us understand what might be going wrong

**Comment by amcp** [comment]
JVM may not shut down even if the main function ends (thread pools may be active elsewhere, the process may have started in daemon mode, etc). It is always good practice to call `System.exit(0)` when you want to be sure that the process dies at the end of your program. Make sure to close() the graph when you are done with it.
