### ISSUE TITLE
Any plans to upgrade to the latest versions of titan and tinkerpop?

### ISSUE THREAD

**Issue by jfstephe** [awslabs/dynamodb-titan-storage-backend#60]
I saw this [old branch](https://github.com/amcp/dynamodb-titan-storage-backend/commit/eca19478704aa6e36fe757f67f4e2308d7f08292) was around and wondered if there were plans to update this library to the latest versions of the tinkerpop and titan?

**Comment by amcp** [comment]
Datastax gave Titan to the community, and JanusGraph picked up in its place. I am on the JanusGraph TSC now, and we are working on getting a release out as our highest priority. As soon as JanusGraph get a release out and have artifacts in Maven I can build against, it would be possible to build this plugin against a much more recent version of TinkerPop.

**Comment by amcp** [comment]
Experimental support can be found in [my fork here](https://github.com/amcp/dynamodb-titan-storage-backend/tree/janusgraph)

**Comment by amcp** [comment]
I will be merging this PR that adds support: https://github.com/awslabs/dynamodb-titan-storage-backend/pull/107 . Closing
