### ISSUE TITLE
Suggestion: Have an official docker image for running this locally/in production

### ISSUE THREAD

**Issue by jfstephe** [awslabs/dynamodb-titan-storage-backend#62]
I'm currently using [this one](https://hub.docker.com/r/soloman1124/dynamodb-titan/) but there are many others. Would be good to have an official one to get started quicker and would probably benefit yourselves as you would know people have 'standard' environments, or you could ask for their's to help reproduce issues.

Just a thought :-)

**Comment by amcp** [comment]
Deployment and configuration needs vary very much among customers. However, I believe adding a Dockerfile to this repository may be possible.

**Comment by amcp** [comment]
Seems like running this in a container will help stabilize some issues others have starting up. I am working on a similar modification for [JanusGraph here](https://github.com/JanusGraph/janusgraph/pull/141) so I'll try and pull it in over here after I am done over there :)

**Comment by amcp** [comment]
@jfstephe https://github.com/JanusGraph/janusgraph/pull/141 is closer to completion.

**Comment by amcp** [comment]
https://docs.docker.com/compose/bundles/ looks interesting as well

**Comment by amcp** [comment]
@jfstephe seems like the easiest way to enable you would be to provide a Dockerfile. The [JanusGraph Dockerization](https://github.com/JanusGraph/janusgraph/pull/141) is in progress, so I think best to wait for that to finish and then pull over here as a point upgrade.
