### ISSUE TITLE
MarvelFactory.load () No such property: graph for class: Script2

### ISSUE THREAD

**Issue by getxperched** [awslabs/dynamodb-titan-storage-backend#63]
I am attempting to follow the steps in Installing and Running the DynamoDB Storage Backend for Titan [@ http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.TitanDB.DownloadingAndRunning.html]

At Step 2: I initially ran into trouble using an AWS Amazon Linux instance because it did not have JDK 1.8 loaded.  I resolved this issue by cloning and installing Oracle Java Standard Edition 1.8.121:  $ javac -version is now javac 1.8.0_121.

This allows me to proceed to Step 10: first 100 lines of the Marvel Universe Social Graph.  At Step 10, I attempted  :> com.amazon.titan.example.MarvelGraphFactory.load(graph, 100, false) from the gremlin> shell.  

I cannot complete Step 10: Gremlin error reads: No such property: graph for class: Script2 

Any idea why this is happening?

Thank you, David

**Comment by getxperched** [comment]
Any help would be very welcome.

**Comment by lukeorland** [comment]
I've experienced this issue a number of times with a local DynamoDB instance, where it randomly gets into this state. Upon deleting and recreating the local DynamoDB instance's data storage, Titan starts working correctly again.

Did anyone experience this problem using the production AWS DynamoDB service?

**Comment by loxtank** [comment]
Deleting and reinstalling does not work for me.
The error gets thrown already at step 7: (I first noticed it in step 10)
`bin/gremlin-server.sh ${PWD}/conf/gremlin-server/gremlin-server-local.yaml`

"
0    [main] INFO  org.apache.tinkerpop.gremlin.server.GremlinServer  -
         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----

222  [main] INFO  org.apache.tinkerpop.gremlin.server.GremlinServer  - Configuring Gremlin Server from /Users/loxtank/opt/bacondb/dynamodb-titan-storage-backend/server/dynamodb-titan100-storage-backend-1.0.0-hadoop1/conf/gremlin-server/gremlin-server-local.yaml
3408 [main] WARN  org.apache.tinkerpop.gremlin.server.GremlinServer  - Graph [graph] configured at [conf/gremlin-server/dynamodb-local.properties] could not be instantiated and will not be available in Gremlin Server.  GraphFactory message: GraphFactory could not instantiate this Graph implementation [class com.thinkaurelius.titan.core.TitanFactory]
java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [class com.thinkaurelius.titan.core.TitanFactory]
"

**Comment by amcp** [comment]
Thank you for the detailed steps to reproduce. I will look into improving the documentation and investigate if there are any dependency fixes needed on our side.

**Comment by getxperched** [comment]
In light of information provided by loxtank and luckorland, I have been using PuTTY to access AWS Amazon Linux from Window 8.1.  I have been using the webservice.  I did not install dynamoDB locally.

Additionally, I ONLY updated the JDK and followed the directions.  'Installing and Running the DynamoDB Storage Backend for Titan' is the first and only thing I have attempted on the  AWS Amazon Linux instance.  

If there are prerequisites not included in the  'Installing and Running the DynamoDB Storage Backend for Titan,' e.g. dynamoDB install or configuration, I have not executed the prerequisites.

**Comment by amcp** [comment]
I am not able to reproduce this issue. I will however add a step to the instructions to install jdk8. Please re-open if you run into this again.

**Comment by czheo** [comment]
Titan was forked to JanusGraph. Use this to load the example data:
```
:> com.amazon.janusgraph.example.MarvelGraphFactory.load(graph, 100, false)
```

**Comment by vijayb2017** [comment]
Tried..   :> com.amazon.janusgraph.example.MarvelGraphFactory.load(graph, 100, false) and got following error..(did not cancel request manually)

Script evaluation exceeded the configured 'scriptEvaluationTimeout' threshold of 30000 ms or evaluation was otherwise cancelled directly for request 

Get the same error even when I try..:> com.amazon.janusgraph.example.MarvelGraphFactory.load(graph, 1, false)
