### ISSUE TITLE
Please make locking in titan vs using dynamoDB locking configurable

### ISSUE THREAD

**Issue by jfstephe** [awslabs/dynamodb-titan-storage-backend#64]
It would be great to have the option to rely on titan's locking and not dynamo's sometimes. Can you give examples of how to configure it one way or the other and specify which is the default please?

Thanks,
John

**Comment by amcp** [comment]
Please see branch `locking` and let us know if you observe the required configurability?

**Comment by amcp** [comment]
resolved
