### ISSUE TITLE
Question about calculateItemSizeInBytes

### ISSUE THREAD

**Issue by hugomarques** [awslabs/dynamodb-titan-storage-backend#7]
Hi team,

I was doing some testing with your methods to calculate the size of a dynamoDB item and I'm getting results beyond 440KB which should be DynamoDB max size for a row.
My data is composed of Strings, Numbers and Dates only. I suspect the problem is on the size of numbers always being assumed to have 21 bytes of size.
Have you guys checked this?

Thanks,
Hugo

**Comment by matthewsowders** [comment]
Hi Hugo,

Could you capture an http request that goes over the limit?  Are you testing against DynamoDB production or DynamoDB Local?

Thank you,
Matthew Sowders

**Comment by hugomarques** [comment]
Hi Matthew,

I can't publish the request since it's amazon internal data, but I was able to figure out the problem is really about the size of numbers.
When I changed the size of numbers to be calculated as if they were simple Strings (1 = 1 byte, 10 = 2 bytes and so on) the size of items matched and my request started to fail only after 400KB as expected.
I can code a sample with some mock data this weekend if you need to clarify.

Regards,
Hugo
