### ISSUE TITLE
Solution for Caused by: java.lang.ClassNotFoundException: com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager

### ISSUE THREAD

**Issue by ainze** [awslabs/dynamodb-titan-storage-backend#74]
When running the README.md step by step on a fresh VM,
you get 
`Caused by: java.lang.ClassNotFoundException: com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager`

after the command `bin/gremlin-server.sh ${PWD}/conf/gremlin-server/gremlin-server-local.yaml`

This was fixed by
` cp ~/dynamodb-titan-storage-backend/target/dynamodb-titan100-storage-backend-1.0.2.jar lib/
`
In other words, a jar is missing when running everything step by step.

**Comment by amcp** [comment]
This might have been fixed by https://github.com/awslabs/dynamodb-titan-storage-backend/commit/6ce1ae09c755f48391f25a3804edc78694a26fbc
I will confirm.

**Comment by amcp** [comment]
I confirmed that the missing JAR issue is fixed. closing
