### ISSUE TITLE
Add DynamoDB to Maven Central

### ISSUE THREAD

**Issue by binaryblake** [awslabs/dynamodb-titan-storage-backend#8]
I'm excited about using TitanDB backed by Dynamo, however I'm unable to get the project up and running. When running maven install, DynamoDB local is unable to be found.

`No versions available for com.amazonaws:DynamoDBLocal:jar:[1.10, 2.0.0) within specified range`

Can we expect DynamoDB local to be added to maven central anytime soon?

**Comment by amcp** [comment]
We are unable to add DynamoDB Local to Maven Central as it is a Binary-only release. Instead, we host our own Maven repository where we serve out DynamoDB Local. The relevant lines in the pom.xml are [here](https://github.com/awslabs/dynamodb-titan-storage-backend/blob/0.5.4/pom.xml#L374).

Please make sure that you run `mvn install` before trying to start DynamoDB Local when you follow the instructions of the README.md.

**Comment by amcp** [comment]
OK to close?

**Comment by amcp** [comment]
Closing.
