### ISSUE TITLE
Recreating (import/export) DynamoDB tables against two different storage.dynamodb.prefix not working

### ISSUE THREAD

**Issue by miteshvp** [awslabs/dynamodb-titan-storage-backend#83]
Hi,
We wanted to recreate our graph database from current set of dynamodb tables with some prefix `prefA` to another set of prefix `prefB`. We used AWS data pipeline to import dynamodb tables with prefix `prefA` to S3 bucket and then exported the same data to another prefix `prefB`. It all went fine. After this, we tried to hook up newly created dynamodb tables by setting storage.dynamodb.prefix=prefB. Unfortunately, we get this error while bringing up the server
```
2731 [main] WARN com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration - Local setting storage.dynamodb.prefix=prefB (Type: FIXED) is overridden by globally managed value (prefA). Use the ManagementSystem interface instead of the local configuration to control this setting. 
```
When I try setting the property via Graph Management API
```
mgmt = graph.openManagement(); mgmt.set('storage.dynamodb.prefix', 'prefB');mgmt.commit();
```
it gave me another error
```
"message": "Cannot change the fixed configuration option: root.storage.dynamodb.prefix", "Exception-Class": "java.lang.IllegalArgumentException"
```

Is there any other way of changing this prefix for GLOBAL?

**Comment by amcp** [comment]
Seems like the prefix config cannot be global if you want to migrate. https://github.com/awslabs/dynamodb-titan-storage-backend#general-dynamodb-configuration-parameters

**Comment by amcp** [comment]
LOCAL: These options only apply to an individual Titan instance and are specified in the configuration provided when initializing the Titan instance.
FIXED: Like GLOBAL, but the value cannot be changed once the Titan cluster is initialized.

Considering the backup use case and the cross-region replication use case, seems like we should not store the prefix in cluster configuration at all. This is probably a bug, so I will fix it in the next release (1.0.4).

**Comment by amcp** [comment]
sees like we will need to change more configuration scopes in light of the new understanding:

- [ ] storage.dynamodb.prefix FIXED -> LOCAL
- [ ] storage.dynamodb.client.endpoint MASKABLE -> LOCAL
- [ ] <add a new configuration> storage.dynamodb.client.signing-region LOCAL

**Comment by amcp** [comment]
@leonhsu1 this will probably reduce the number of writes you saw to system_properties in replica stacks

**Comment by amcp** [comment]
@miteshvp Fixed in 3ad5618b06fc1772700a0df46350224c25378270, can you check it out please?

**Comment by amcp** [comment]
I performed upgrade downgrade testing between a graph created at 1.0.4, without the config scope changes, launched a 1.0.5 stack on top of the 1.0.4 graph, and was able to run through the Marvel walkthrough without exceptions:

196  [main] INFO  org.apache.tinkerpop.gremlin.server.GremlinServer  - Configuring Gremlin Server from /Users/amcp/dynamodb-titan-storage-backend/server/dynamodb-titan100-storage-backend-1.0.5-hadoop1/conf/gremlin-server/gremlin-server-local.yaml
2598 [main] INFO  com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader  - Loaded and initialized config classes: 12 OK out of 12 attempts in PT0.07S
3185 [main] INFO  com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration  - Generated unique-instance-id=0a423f1e43504-4c3275931755-ant-amazon-com1
3214 [main] INFO  com.thinkaurelius.titan.diskstorage.Backend  - Configuring index [search]
3288 [main] INFO  com.thinkaurelius.titan.diskstorage.es.ElasticSearchSetup  - Creating ES directory prefix: elasticsearch
3288 [main] INFO  com.thinkaurelius.titan.diskstorage.es.ElasticSearchSetup  - Creating ES data directory: elasticsearch/data
3288 [main] INFO  com.thinkaurelius.titan.diskstorage.es.ElasticSearchSetup  - Creating ES work directory: elasticsearch/work
3288 [main] INFO  com.thinkaurelius.titan.diskstorage.es.ElasticSearchSetup  - Creating ES logs directory: elasticsearch/logs
3528 [main] INFO  org.elasticsearch.node  - [Captain UK] version[1.5.1], pid[43504], build[5e38401/2015-04-09T13:41:35Z]
3528 [main] INFO  org.elasticsearch.node  - [Captain UK] initializing ...
3534 [main] INFO  org.elasticsearch.plugins  - [Captain UK] loaded [], sites []
6263 [main] INFO  org.elasticsearch.node  - [Captain UK] initialized
6264 [main] INFO  org.elasticsearch.node  - [Captain UK] starting ...
6267 [main] INFO  org.elasticsearch.transport  - [Captain UK] bound_address {local[1]}, publish_address {local[1]}
6295 [main] INFO  org.elasticsearch.discovery  - [Captain UK] elasticsearch/mM02Pbh7SpOFldcyr8V-IA
6297 [elasticsearch[Captain UK][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.service  - [Captain UK] master {new [Captain UK][mM02Pbh7SpOFldcyr8V-IA][4c3275931755.ant.amazon.com][local[1]]{local=true}}, removed {[Captain UK][0Mr4uN8WRveanUXDlKkE-g][4c3275931755.ant.amazon.com][local[1]]{local=true},}, reason: local-disco-initial_connect(master)
6387 [elasticsearch[Captain UK][clusterService#updateTask][T#1]] INFO  org.elasticsearch.gateway  - [Captain UK] recovered [0] indices into cluster_state
6437 [main] INFO  org.elasticsearch.http  - [Captain UK] bound_address {inet[/0:0:0:0:0:0:0:0:9201]}, publish_address {inet[/10.66.70.119:9201]}
6437 [main] INFO  org.elasticsearch.node  - [Captain UK] started
6724 [elasticsearch[Captain UK][clusterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.metadata  - [Captain UK] [titan] creating index, cause [api], templates [], shards [5]/[1], mappings []
7186 [main] INFO  com.thinkaurelius.titan.diskstorage.Backend  - Initiated backend operations thread pool of size 8
7330 [main] INFO  com.thinkaurelius.titan.diskstorage.log.kcvs.KCVSLog  - Loaded unidentified ReadMarker start time 2017-04-21T13:13:32.606Z into com.thinkaurelius.titan.diskstorage.log.kcvs.KCVSLog$MessagePuller@699d96bc
7330 [main] INFO  org.apache.tinkerpop.gremlin.server.GremlinServer  - Graph [graph] was successfully configured via [conf/gremlin-server/dynamodb-local.properties].
7330 [main] INFO  org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor  - Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-*
7692 [main] INFO  org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines  - Loaded nashorn ScriptEngine
8283 [main] INFO  org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines  - Loaded gremlin-groovy ScriptEngine
9193 [main] INFO  org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor  - Initialized gremlin-groovy ScriptEngine with scripts/empty-sample.groovy
9193 [main] INFO  org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor  - Initialized GremlinExecutor and configured ScriptEngines.
9201 [main] INFO  org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor  - A GraphTraversalSource is now bound to [g] with graphtraversalsource[standardtitangraph[com.amazon.titan.diskstorage.dynamodb.DynamoDBStoreManager:[127.0.0.1]], standard]
9284 [main] INFO  org.apache.tinkerpop.gremlin.server.AbstractChannelizer  - Configured application/vnd.gremlin-v1.0+gryo with org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0
9284 [main] INFO  org.apache.tinkerpop.gremlin.server.AbstractChannelizer  - Configured application/vnd.gremlin-v1.0+gryo-stringd with org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0
9317 [main] INFO  org.apache.tinkerpop.gremlin.server.AbstractChannelizer  - Configured application/vnd.gremlin-v1.0+json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0
9319 [main] INFO  org.apache.tinkerpop.gremlin.server.AbstractChannelizer  - Configured application/json with org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0
9416 [gremlin-server-boss-1] INFO  org.apache.tinkerpop.gremlin.server.GremlinServer  - Gremlin Server configured with worker thread pool of 1, gremlin pool of 8 and boss thread pool of 1.
9416 [gremlin-server-boss-1] INFO  org.apache.tinkerpop.gremlin.server.GremlinServer  - Channel started at port 8182.
90870 [gremlin-server-worker-1] INFO  org.apache.tinkerpop.gremlin.server.op.OpLoader  - Adding the standard OpProcessor.
90872 [gremlin-server-worker-1] INFO  org.apache.tinkerpop.gremlin.server.op.OpLoader  - Adding the control OpProcessor.
90875 [gremlin-server-worker-1] INFO  org.apache.tinkerpop.gremlin.server.op.OpLoader  - Adding the session OpProcessor.
91288 [gremlin-server-exec-1] WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [((weapon = shield OR weapon = claws))]. For better performance, use indexes

**Comment by amcp** [comment]
@leonhsu1 @miteshvp I just ran a similar test using the scripts in https://github.com/awslabs/dynamodb-titan-storage-backend/pull/86 to confirm that even when I copy a 1.0.4 graph to a different table prefix and start a 1.0.5 gremlin server on it, I am able to read and write the graph using 1.0.5 with no issues or errors. Closing for now, please reopen if you have more issues.

**Comment by miteshvp** [comment]
Thanks guys for the quick fix. I am not able to test this yet, but i will surely update once i am able to.

**Comment by miteshvp** [comment]
@amcp one quick question - Will this work on currently taken backups? Or do I need to create a fresh backup after upgrading to 1.0.5? Is there any work-around to use the existing backups and not re-create the graph entirely?

**Comment by miteshvp** [comment]
@amcp - I tried to left out only system_properties table but imported all other tables. Then when I start gremlin server, it creates system_properties tables and seems to be working fine. It is picking up right indices and I sell all the data as well. Is this a good work-around? Will it create any problems?

**Comment by amcp** [comment]
@miteshvp Titan will not try to update LOCAL scope configuration even if the configuration exists in `system_properties`. I would advise to copy system_properties as well unless you are running into other issues.

**Comment by miteshvp** [comment]
@amcp my problem is this fix will work for future backup/migration, but not for the current backups that I want to restore. I agree, it is not the cleanest solution, but from what I can tell, it is behaving exactly the same, and now also talks to the right set of tables. But having said that, I will definitely like to move to the latest version for any future backups/migrations.
