### ISSUE TITLE
Stop emitting metrics during the SingleGraphTest module

### ISSUE THREAD

**Issue by amcp** [awslabs/dynamodb-titan-storage-backend#96]
https://travis-ci.org/awslabs/dynamodb-titan-storage-backend/jobs/226377198

**Comment by F2006** [comment]
This should be fixed with https://github.com/awslabs/dynamodb-titan-storage-backend/pull/102

**Comment by amcp** [comment]
Verified that tests do not print metrics anymore, closing.
